import type { Experience, Page, Post, Profile, Tech, Work } from '@/lib/models'

/**
 * Real v1 content, promoted out of code and into data.
 *
 * Everything here came from the v1 app at tag `v1-final`: src/data/projects.jsx,
 * src/data/techstack.jsx, and the identity strings that were scattered across
 * components/Home.jsx, apps/Contact/ContactCard.jsx and apps/Me/components/*.
 * The prose is Emanuel's own, not rewritten.
 *
 * Two uses, one source:
 *   1. `npm run seed` writes these into MongoDB.
 *   2. When MONGODB_URI is unset, lib/content serves them directly so the site
 *      runs with no database configured.
 *
 * Nothing here is invented. Where a real value is unknown it is left null or
 * empty rather than filled in.
 */

const T = (slug: string) => `tech_${slug}`

export const seedTech: Tech[] = [
  {
    slug: 'nodejs',
    name: 'Node.js',
    category: 'Framework',
    firstEncounter: 2024,
    note: 'My favorite for backend framework Express, REST APIs, and full control with npm.',
    rank: 1,
    icon: { simpleIconsSlug: 'nodedotjs', devicon: 'nodejs', color: '#5FA04E' },
    featured: true,
    order: 1,
  },
  {
    slug: 'python',
    name: 'Python',
    category: 'Language',
    firstEncounter: 2022,
    note: "Clean syntax and quick to prototype with. I use it for interview prep. It's just satisfying to work with.",
    rank: 2,
    icon: { simpleIconsSlug: 'python', devicon: 'python', color: '#3776AB' },
    featured: true,
    order: 2,
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    category: 'Database',
    firstEncounter: 2024,
    note: 'Love how intuitive it is to work with documents, especially alongside Node.js.',
    rank: 3,
    icon: { simpleIconsSlug: 'mongodb', devicon: 'mongodb', color: '#47A248' },
    featured: true,
    order: 3,
  },
  {
    slug: 'javascript',
    name: 'JavaScript',
    category: 'Language',
    firstEncounter: 2023,
    note: "Started with vanilla JS, now can't imagine web dev without it.",
    rank: null,
    icon: { simpleIconsSlug: 'javascript', devicon: 'javascript', color: '#F7DF1E' },
    featured: false,
    order: 10,
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    category: 'Language',
    firstEncounter: 2025,
    note: 'The stack I am committing to. Types catch the mistakes I actually make.',
    rank: null,
    icon: { simpleIconsSlug: 'typescript', devicon: 'typescript', color: '#3178C6' },
    featured: false,
    order: 11,
  },
  {
    slug: 'react',
    name: 'React',
    category: 'Framework',
    firstEncounter: 2024,
    note: 'Hooks changed everything, functional components are so clean.',
    rank: null,
    icon: { simpleIconsSlug: 'react', devicon: 'react', color: '#61DAFB' },
    featured: false,
    order: 12,
  },
  {
    slug: 'express',
    name: 'Express',
    category: 'Framework',
    firstEncounter: 2025,
    note: 'Minimal and unopinionated, perfect for learning backend concepts.',
    rank: null,
    icon: { simpleIconsSlug: 'express', devicon: 'express', color: '#000000' },
    featured: false,
    order: 13,
  },
  {
    slug: 'tailwind',
    name: 'Tailwind CSS',
    category: 'Framework',
    firstEncounter: 2024,
    note: 'Utility-first changed how I think about styling.',
    rank: null,
    icon: { simpleIconsSlug: 'tailwindcss', devicon: 'tailwindcss', color: '#06B6D4' },
    featured: false,
    order: 14,
  },
  {
    slug: 'cpp',
    name: 'C++',
    category: 'Language',
    firstEncounter: 2020,
    note: 'First love in programming. A very strict one.',
    rank: null,
    icon: { simpleIconsSlug: 'cplusplus', devicon: 'cplusplus', color: '#00599C' },
    featured: false,
    order: 15,
  },
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    category: 'Database',
    firstEncounter: null,
    note: 'Learning next. Relational modelling and the query planner.',
    rank: null,
    icon: { simpleIconsSlug: 'postgresql', devicon: 'postgresql', color: '#4169E1' },
    featured: false,
    order: 16,
  },
  {
    slug: 'git',
    name: 'Git',
    category: 'Tool',
    firstEncounter: 2023,
    note: 'Every single project.',
    rank: null,
    icon: { simpleIconsSlug: 'git', devicon: 'git', color: '#F05032' },
    featured: false,
    order: 17,
  },
  {
    slug: 'nextjs',
    name: 'Next.js',
    category: 'Framework',
    firstEncounter: 2025,
    note: 'What this site runs on. Server components and rendering that crawlers can read.',
    rank: null,
    icon: { simpleIconsSlug: 'nextdotjs', devicon: 'nextjs', color: '#000000' },
    featured: false,
    order: 18,
  },
] as unknown as Tech[]

export const seedProfile: Profile = {
  name: 'Emanuel Molla',
  givenName: 'Emanuel',
  familyName: 'Molla',
  alternateName: 'emanuelmolla',
  headline: 'Backend developer',
  bio: {
    short:
      'Backend developer in Surrey, BC. Computer Systems Technology at BCIT, working mostly on the server side.',
    long: [
      'I love solving real problems with code, building tools that help people, and constantly learning how technology works behind the scenes.',
      '',
      'I grew up in Ethiopia, where I developed my love for learning and problem-solving. At 21 I moved to Canada, and I could not be more grateful for the journey.',
      '',
      'My faith through the Ethiopian Orthodox Church plays a huge role in shaping who I am. It guides my values, keeps me grounded, and reminds me to approach life with gratitude and purpose.',
    ].join('\n'),
  },
  location: { city: 'Surrey', region: 'BC', country: 'Canada' },
  avatar: {
    url: '/image.jpg',
    alt: 'Emanuel Molla',
    width: 3024,
    height: 4032,
    blurDataURL: null,
    caption: null,
  },
  links: [
    { kind: 'github', label: 'GitHub', url: 'https://github.com/emanuelmolla', handle: 'emanuelmolla', order: 1, visible: true },
    { kind: 'linkedin', label: 'LinkedIn', url: 'https://www.linkedin.com/in/emanuel-molla', handle: 'emanuel-molla', order: 2, visible: true },
    { kind: 'email', label: 'Email', url: 'mailto:emanuelmolla@outlook.com', handle: 'emanuelmolla@outlook.com', order: 3, visible: true },
    { kind: 'resume', label: 'Resume', url: '/resume.pdf', handle: null, order: 4, visible: true },
  ],
  availability: { status: 'selective', availableFrom: null, note: null },
  resumeUrl: '/resume.pdf',
  knowsAbout: ['Backend development', 'REST APIs', 'Node.js', 'MongoDB', 'Systems design'],
  knowsLanguage: ['en', 'am'],
  inLanguage: 'en',
  seo: {
    title: 'Emanuel Molla',
    description:
      'Backend developer in Surrey, BC. Computer Systems Technology at BCIT.',
    ogImage: null,
    canonicalUrl: null,
    noindex: false,
  },
} as unknown as Profile

export const seedWork: Work[] = [
  {
    slug: 'devnest',
    previousSlugs: [],
    kind: 'software',
    title: 'DevNest',
    summary:
      'Sprint-based project management with task tracking, notes and goals. Uses the Gemini API to generate sprint tasks and feature plans.',
    body: '',
    bodyFormat: 'markdown',
    problem: null,
    outcome: null,
    role: 'Solo Developer',
    isGroup: false,
    teamSize: null,
    startDate: new Date('2025-07-01'),
    endDate: null,
    datePrecision: 'month',
    circa: false,
    dateOverride: null,
    lifecycle: 'active',
    status: 'published',
    publishedAt: new Date('2025-07-01'),
    featuredOrder: 1,
    techRefs: [T('express'), T('mongodb'), T('react'), T('nodejs')],
    tags: ['side-project'],
    links: [
      { kind: 'repo', label: 'Repository', url: 'https://github.com/emanuelmolla/DevNest' },
      { kind: 'live', label: 'Live', url: 'https://devnest.molla.dev' },
    ],
    coverImage: null,
    mediaRefs: [],
    relatedPostRef: null,
    details: {
      kind: 'software',
      stack: ['React', 'Express', 'MongoDB', 'Gemini API', 'JWT', 'Auth0', 'Node.js', 'Tailwind CSS'],
      architectureNotes: null,
      repoUrl: 'https://github.com/emanuelmolla/DevNest',
      liveUrl: 'https://devnest.molla.dev',
    },
    seo: { title: null, description: null, ogImage: null, canonicalUrl: null, noindex: false },
  },
  {
    slug: 'scholiast',
    previousSlugs: [],
    kind: 'software',
    title: 'Scholiast',
    summary:
      'A student productivity platform with flashcards, resource management and weekly goal tracking. I built the backend.',
    body: '',
    bodyFormat: 'markdown',
    problem: null,
    outcome: null,
    role: 'Backend Developer',
    isGroup: true,
    teamSize: null,
    startDate: new Date('2025-05-01'),
    endDate: null,
    datePrecision: 'month',
    circa: false,
    dateOverride: null,
    lifecycle: 'shipped',
    status: 'published',
    publishedAt: new Date('2025-05-01'),
    featuredOrder: 2,
    techRefs: [T('nodejs'), T('express'), T('mongodb'), T('react')],
    tags: ['team-project'],
    links: [
      { kind: 'repo', label: 'Repository', url: 'https://github.com/emanuelmolla/Scholiast' },
      { kind: 'live', label: 'Live', url: 'https://sholiast.webios.link' },
    ],
    coverImage: null,
    mediaRefs: [],
    relatedPostRef: null,
    details: {
      kind: 'software',
      stack: ['React', 'Express', 'Node.js', 'MongoDB', 'Auth0', 'Gemini API', 'Tailwind CSS'],
      architectureNotes: null,
      repoUrl: 'https://github.com/emanuelmolla/Scholiast',
      liveUrl: 'https://sholiast.webios.link',
    },
    seo: { title: null, description: null, ogImage: null, canonicalUrl: null, noindex: false },
  },
  {
    slug: 'bookpinion-api',
    previousSlugs: [],
    kind: 'software',
    title: 'BookPinion API',
    summary:
      'A REST API for managing book reviews. Advanced book search, review storage, and role-based access control.',
    body: '',
    bodyFormat: 'markdown',
    problem: null,
    outcome: null,
    role: 'Solo Developer',
    isGroup: false,
    teamSize: null,
    startDate: new Date('2025-06-01'),
    endDate: null,
    datePrecision: 'month',
    circa: false,
    dateOverride: null,
    lifecycle: 'shipped',
    status: 'published',
    publishedAt: new Date('2025-06-01'),
    featuredOrder: 3,
    techRefs: [T('nodejs'), T('express'), T('mongodb')],
    tags: ['api'],
    links: [
      { kind: 'repo', label: 'Repository', url: 'https://github.com/emanuelmolla/BookPinion-API' },
      { kind: 'live', label: 'Live', url: 'https://bookpinion-api.onrender.com' },
    ],
    coverImage: null,
    mediaRefs: [],
    relatedPostRef: null,
    details: {
      kind: 'software',
      stack: ['Node.js', 'Express', 'MongoDB', 'JWT', 'Mongoose'],
      architectureNotes: null,
      repoUrl: 'https://github.com/emanuelmolla/BookPinion-API',
      liveUrl: 'https://bookpinion-api.onrender.com',
    },
    seo: { title: null, description: null, ogImage: null, canonicalUrl: null, noindex: false },
  },
  {
    slug: 'portfolio',
    previousSlugs: [],
    kind: 'software',
    title: 'This site',
    summary:
      'A server-rendered portfolio with a content model that any number of themes can render. The desktop theme here is the previous version of this site, rebuilt.',
    body: '',
    bodyFormat: 'markdown',
    problem: null,
    outcome: null,
    role: 'Designer & Developer',
    isGroup: false,
    teamSize: null,
    startDate: new Date('2025-06-25'),
    endDate: null,
    datePrecision: 'day',
    circa: false,
    dateOverride: null,
    lifecycle: 'active',
    status: 'published',
    publishedAt: new Date('2025-06-25'),
    featuredOrder: 4,
    techRefs: [T('nextjs'), T('typescript'), T('mongodb'), T('tailwind')],
    tags: ['side-project'],
    links: [
      { kind: 'repo', label: 'Repository', url: 'https://github.com/emanuelmolla/Portfolio' },
      { kind: 'live', label: 'Live', url: 'https://emanuelmolla.dev' },
    ],
    coverImage: null,
    mediaRefs: [],
    relatedPostRef: null,
    details: {
      kind: 'software',
      stack: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind CSS'],
      architectureNotes: null,
      repoUrl: 'https://github.com/emanuelmolla/Portfolio',
      liveUrl: 'https://emanuelmolla.dev',
    },
    seo: { title: null, description: null, ogImage: null, canonicalUrl: null, noindex: false },
  },
] as unknown as Work[]

export const seedExperience: Experience[] = [
  {
    slug: 'bcit-cst',
    section: 'education',
    sortMode: 'date-desc',
    org: 'British Columbia Institute of Technology',
    role: 'Computer Systems Technology',
    location: 'Burnaby, BC',
    employmentType: null,
    url: 'https://www.bcit.ca',
    startDate: null,
    endDate: null,
    current: true,
    summary: null,
    highlights: [],
    techRefs: [],
    links: [],
    order: 1,
    status: 'published',
  },
  {
    slug: 'bahir-dar-university',
    section: 'education',
    sortMode: 'date-desc',
    org: 'Bahir Dar University',
    role: 'Studied in Ethiopia',
    location: 'Bahir Dar, Ethiopia',
    employmentType: null,
    url: null,
    startDate: null,
    endDate: null,
    current: false,
    summary: null,
    highlights: [],
    techRefs: [T('cpp')],
    links: [],
    order: 2,
    status: 'published',
  },
] as unknown as Experience[]

export const seedPages: Page[] = [
  {
    slug: 'about',
    previousSlugs: [],
    title: 'About',
    body: '',
    bodyFormat: 'markdown',
    sections: [],
    status: 'published',
    inNav: true,
    navOrder: 3,
    showUpdatedAt: false,
    seo: { title: null, description: null, ogImage: null, canonicalUrl: null, noindex: false },
  },
] as unknown as Page[]

/**
 * Empty on purpose. The real posts live in the v1 Atlas `Blog` collection and
 * arrive via the migration. Inventing post titles to fill a section would be
 * exactly the kind of thing this project is trying not to do.
 */
export const seedPosts: Post[] = []
